### ISSUE TITLE
OnClickListeners

### ISSUE THREAD

**Issue by Akitektuo** [marasavanna/AnimalAdoption#2]
You can import the method throw an interface so you can use this instead of new and you can identify the clicked object by id

**Comment by marasavanna** [comment]
I think it is "implement the interface so you can access designed methods directly instead of creating new instances of associated objects". "Import" is used for packages and files, while "throw" keyword for exceptions.

**Comment by Akitektuo** [comment]
Well you kind of have to import the package for the interface =)))
